#ifndef _TIMER_H
#define _TIMER_H

#define IRS_TIMER 0x08
#define USR_TIMER 0x1C
#define MAX_TIMERS 5

#define TIMER_AUDIO_CALLBACK 0
#define TIMER_AUDIO_TIME 20
#define TIMER_VIDEO_CALLBACK 1
#define TIMER_VIDEO_TIME 50
#define TIMER_MISC_CALLBACK 2
#define TIMER_MISC_TIME 100

#endif// _TIMER_H