
#define SPRITE_HIT_COLOR 241


#define FP 16// fraction bits
#define FONT_SLIM_GFX_WIDTH 128
#define FONT_SLIM_GFX_HEIGHT 32
#define FONT_BIG_GFX_WIDTH 256
#define FONT_BIG_GFX_HEIGHT 64
#define FONT_TRANSPARENT_COLOR 220
#define FONT_ASCII_CODE_N 165

#define FONT_SLIM_BLACK 0
#define FONT_SLIM_WHITE 1
#define FONT_BIG_WHITE 2
#define FONT_BIG_BLACK 3

#define SPRITE_GRAPHICS_ID_CURSOR 1
#define SPRITE_GRAPHICS_ID_AIM 2
#define SPRITE_GRAPHICS_ID_ACTOR 3
#define SPRITE_GRAPHICS_ID_ACTORC 4
#define SPRITE_GRAPHICS_ID_ACTOR_PORTAIT 5
#define SPRITE_GRAPHICS_ID_BULLET1 6
#define SPRITE_GRAPHICS_ID_BULLET2 7
#define SPRITE_GRAPHICS_ID_BULLET3 8
#define SPRITE_GRAPHICS_ID_ENEMY1 9
#define SPRITE_GRAPHICS_ID_ENEMY1_PORTAIT 10
#define SPRITE_GRAPHICS_ID_ENEMY2 11
#define SPRITE_GRAPHICS_ID_ENEMY2_PORTAIT 12
#define SPRITE_GRAPHICS_ID_ENEMY3 13
#define SPRITE_GRAPHICS_ID_ENEMY3_PORTAIT 14
#define SPRITE_GRAPHICS_ID_ENEMY4 15
#define SPRITE_GRAPHICS_ID_ENEMY4_PORTAIT 16
#define SPRITE_GRAPHICS_ID_ENEMY_BULLET 17
#define SPRITE_GRAPHICS_ID_BARREL1 18
#define SPRITE_GRAPHICS_ID_BARREL1_PORTAIT 19
#define SPRITE_GRAPHICS_ID_BARREL2 20
#define SPRITE_GRAPHICS_ID_BARREL2_PORTAIT 21
#define SPRITE_GRAPHICS_ID_BARREL3 22
#define SPRITE_GRAPHICS_ID_BARREL3_PORTAIT 23
#define SPRITE_GRAPHICS_ID_GRENADE1 24
#define SPRITE_GRAPHICS_ID_GRENADE2 25
#define SPRITE_GRAPHICS_ID_MISILE1 26
#define SPRITE_GRAPHICS_ID_MISILE2 27
#define SPRITE_GRAPHICS_ID_LIFEBAR 28
#define SPRITE_GRAPHICS_ID_FIRE1 29
#define SPRITE_GRAPHICS_ID_ELECTRIC1 30
#define SPRITE_GRAPHICS_ID_TEMP 31
#define SPRITE_GRAPHICS_ID_BTN_NEW 32
#define SPRITE_GRAPHICS_ID_BTN_LOAD 33
#define SPRITE_GRAPHICS_ID_BTN_OPTIONS 34
#define SPRITE_GRAPHICS_ID_BTN_CREDITS 35
#define SPRITE_GRAPHICS_ID_BTN_EXIT 36
#define SPRITE_GRAPHICS_ID_TITLE 37
#define SPRITE_GRAPHICS_ID_CHAT 38
#define SPRITE_GRAPHICS_ID_ACTORCHAT 39
#define SPRITE_GRAPHICS_ID_PUNCH_EFFECT 40
#define SPRITE_GRAPHICS_ID_BLOOD 41
