
#define ENEMY_TRANSP_COLOR 220

#define ENEMY_MAX_ENEMIES 5
#define ENEMY_MAX_BULLETS 64

#define ENEMY_BULLET_GFX_WIDTH 32
#define ENEMY_BULLET_GFX_HEIGHT 8
#define ENEMY_BULLET_WIDTH 8
#define ENEMY_BULLET_HEIGHT 8
#define ENEMY_BULLET_SPEED 15

#define ENEMY_SPEED 2

#define ENEMY_ANIMATION_SPEED 4

#define ENEMY_IDLE_TICKS 120

#define ENEMY_ACTION_STAND 1
#define ENEMY_ACTION_LOOP 2
#define ENEMY_ACTION_SHOOT 3
#define ENEMY_ACTION_WALK 4
#define ENEMY_ACTION_PUNCH 5

#define ENEMY_GUN_BARE_HANDS 0
#define ENEMY_GUN_PISTOL 1
#define ENEMY_GUN_RIFLE 2
#define ENEMY_GUN_SHOTGUN 3
#define ENEMY_GUN_AK 4
#define ENEMY_GUN_MISILE 5

#define ENEMY_FACING_RIGHT 1
#define ENEMY_FACING_LEFT 2
#define ENEMY_FACING_DOWN 4
#define ENEMY_FACING_UP 8

#define ENEMY_STATUS_SLEEP 1
#define ENEMY_STATUS_WAKEUP 2
#define ENEMY_STATUS_WARNING 3
#define ENEMY_STATUS_ALERT 4
#define ENEMY_STATUS_RAMPAGE 5

#define ENEMY_UP_STAND_BASE_FRAME 0
#define ENEMY_UP_WALK_BASE_FRAME 1
#define ENEMY_UP_PUNCH_BASE_FRAME 5
#define ENEMY_UP_SHOOT_BASE_FRAME 5
#define ENEMY_UP_HIT_BASE_FRAME 8

#define ENEMY_UP_RIGHT_STAND_BASE_FRAME 10
#define ENEMY_UP_RIGHT_WALK_BASE_FRAME 11
#define ENEMY_UP_RIGHT_PUNCH_BASE_FRAME 15
#define ENEMY_UP_RIGHT_SHOOT_BASE_FRAME 15
#define ENEMY_UP_RIGHT_HIT_BASE_FRAME 18

#define ENEMY_RIGHT_STAND_BASE_FRAME 20
#define ENEMY_RIGHT_WALK_BASE_FRAME 21
#define ENEMY_RIGHT_PUNCH_BASE_FRAME 25
#define ENEMY_RIGHT_SHOOT_BASE_FRAME 25
#define ENEMY_RIGHT_HIT_BASE_FRAME 28

#define ENEMY_DOWN_RIGHT_STAND_BASE_FRAME 30
#define ENEMY_DOWN_RIGHT_WALK_BASE_FRAME 31
#define ENEMY_DOWN_RIGHT_PUNCH_BASE_FRAME 35
#define ENEMY_DOWN_RIGHT_SHOOT_BASE_FRAME 35
#define ENEMY_DOWN_RIGHT_HIT_BASE_FRAME 38

#define ENEMY_DOWN_STAND_BASE_FRAME 40
#define ENEMY_DOWN_WALK_BASE_FRAME 41
#define ENEMY_DOWN_PUNCH_BASE_FRAME 45
#define ENEMY_DOWN_SHOOT_BASE_FRAME 45
#define ENEMY_DOWN_HIT_BASE_FRAME 48

#define ENEMY_DIE_BASE_FRAME 50