
#define ENEMY_TRANSP_COLOR 220

#define ENEMY_MAX_ENEMIES 5
#define ENEMY_MAX_BULLETS 64

#define ENEMY_BULLET_GFX_WIDTH 32
#define ENEMY_BULLET_GFX_HEIGHT 8
#define ENEMY_BULLET_WIDTH 8
#define ENEMY_BULLET_HEIGHT 8
#define ENEMY_BULLET_SPEED 15

#define ENEMY_ANIMATION_SPEED 2

#define ENEMY_GUN_BARE_HANDS 0
#define ENEMY_GUN_PISTOL 1
#define ENEMY_GUN_RIFLE 2
#define ENEMY_GUN_SHOTGUN 3
#define ENEMY_GUN_AK 4
#define ENEMY_GUN_MISILE 5

#define ENEMY_FACING_RIGHT 1
#define ENEMY_FACING_LEFT 2
#define ENEMY_FACING_DOWN 4
#define ENEMY_FACING_UP 8