#ifndef ACTOR_H
#define ACTOR_H

#include "../types/types.h"

#define ACTOR_TRANSP_COLOR 201
#define ACTOR_SPRITE_WIDTH 32
#define ACTOR_SPRITE_HEIGHT 32
#define ACTOR_TILESET_WIDTH 320
#define ACTOR_TILESET_HEIGHT 288
#define ACTOR_BULLET_GFX_WIDTH 32
#define ACTOR_BULLET_GFX_HEIGHT 8
#define ACTOR_BULLET_WIDTH 8
#define ACTOR_BULLET_HEIGHT 8
#define ACTOR_BULLET_ANIM_SPEED 4
#define ACTOR_SPEED 4
#define ACTOR_ANIMATION_SPEED 4
#define ACTOR_LOOP_ANIMATION_SPEED 3
#define ACTOR_PUNCH_ANIMATION_SPEED 5d
#define ACTOR_ACCURACY_SPEED 5
#define ACTOR_IDLE_TICKS 120
#define ACTOR_MAX_ACCURACY 4
#define ACTOR_ACCURACY_DELAY 4
#define ACTOR_LIFE 400
#define ACTOR_GRENADES_MAX_DISTANCE 150
#define ACTOR_GRENADES_MAX_TIME 3

#define ACTOR_FACING_RIGHT 1
#define ACTOR_FACING_LEFT 2
#define ACTOR_FACING_DOWN 4
#define ACTOR_FACING_DOWN_RIGHT 5
#define ACTOR_FACING_DOWN_LEFT 6
#define ACTOR_FACING_UP 8
#define ACTOR_FACING_UP_RIGHT 9
#define ACTOR_FACING_UP_LEFT 10

#define ACTOR_ACTION_STAND 1
#define ACTOR_ACTION_LOOP 2
#define ACTOR_ACTION_SHOOT 3
#define ACTOR_ACTION_WALK 4
#define ACTOR_ACTION_PUNCH 5
#define ACTOR_ACTION_CHANGE_GUN 6
#define ACTOR_ACTION_RELOAD 7
#define ACTOR_ACTION_THROW 8

#define ACTOR_GUN_TYPE_BARE_HANDS 0
#define ACTOR_GUN_TYPE_PISTOL 1
#define ACTOR_GUN_TYPE_SHOTGUN 2
#define ACTOR_GUN_TYPE_UZI 3
#define ACTOR_GUN_TYPE_SNIPPER 4

#define ACTOR_ANIM_FEET_INDEX 0
#define ACTOR_ANIM_BODY_INDEX 1
#define ACTOR_ANIM_HEAD_INDEX 2
#define ACTOR_ANIM_LARM_INDEX 3
#define ACTOR_ANIM_RARM_INDEX 4

#define ACTOR_ANIM_STAND_UP 1
#define ACTOR_ANIM_STAND_UP_RIGHT 2
#define ACTOR_ANIM_STAND_RIGHT 3
#define ACTOR_ANIM_STAND_DOWN_RIGHT 4
#define ACTOR_ANIM_STAND_DOWN 5
#define ACTOR_ANIM_STAND_DOWN_LEFT 6
#define ACTOR_ANIM_STAND_LEFT 7
#define ACTOR_ANIM_STAND_UP_LEFT 8

#define ACTOR_ANIM_WALK_UP 9
#define ACTOR_ANIM_WALK_UP_RIGHT 10
#define ACTOR_ANIM_WALK_RIGHT 11
#define ACTOR_ANIM_WALK_DOWN_RIGHT 12
#define ACTOR_ANIM_WALK_DOWN 13
#define ACTOR_ANIM_WALK_DOWN_LEFT 14
#define ACTOR_ANIM_WALK_LEFT 15
#define ACTOR_ANIM_WALK_UP_LEFT 16

#define ACTOR_ANIM_LOOP_UP 17
#define ACTOR_ANIM_LOOP_RIGHT 18
#define ACTOR_ANIM_LOOP_DOWN 19
#define ACTOR_ANIM_LOOP_LEFT 20

#define ACTOR_ANIM_PUNCH1_UP 21
#define ACTOR_ANIM_PUNCH1_UP_RIGHT 22
#define ACTOR_ANIM_PUNCH1_RIGHT 23
#define ACTOR_ANIM_PUNCH1_DOWN_RIGHT 24
#define ACTOR_ANIM_PUNCH1_DOWN 25
#define ACTOR_ANIM_PUNCH1_DOWN_LEFT 26
#define ACTOR_ANIM_PUNCH1_LEFT 27
#define ACTOR_ANIM_PUNCH1_UP_LEFT 28

#define ACTOR_ANIM_PUNCH2_UP 29
#define ACTOR_ANIM_PUNCH2_UP_RIGHT 30
#define ACTOR_ANIM_PUNCH2_RIGHT 31
#define ACTOR_ANIM_PUNCH2_DOWN_RIGHT 32
#define ACTOR_ANIM_PUNCH2_DOWN 33
#define ACTOR_ANIM_PUNCH2_DOWN_LEFT 34
#define ACTOR_ANIM_PUNCH2_LEFT 35
#define ACTOR_ANIM_PUNCH2_UP_LEFT 36

#define ACTOR_ANIM_KICK_UP 37
#define ACTOR_ANIM_KICK_UP_RIGHT 38
#define ACTOR_ANIM_KICK_RIGHT 39
#define ACTOR_ANIM_KICK_DOWN_RIGHT 40
#define ACTOR_ANIM_KICK_DOWN 41
#define ACTOR_ANIM_KICK_DOWN_LEFT 42
#define ACTOR_ANIM_KICK_LEFT 43
#define ACTOR_ANIM_KICK_UP_LEFT 44

#define ACTOR_ANIM_FIGHT_UP 45
#define ACTOR_ANIM_FIGHT_UP_RIGHT 46
#define ACTOR_ANIM_FIGHT_RIGHT 47
#define ACTOR_ANIM_FIGHT_DOWN_RIGHT 48
#define ACTOR_ANIM_FIGHT_DOWN 49
#define ACTOR_ANIM_FIGHT_DOWN_LEFT 50
#define ACTOR_ANIM_FIGHT_LEFT 51
#define ACTOR_ANIM_FIGHT_UP_LEFT 52

#define ACTOR_ANIM_SHOT_UP 53
#define ACTOR_ANIM_SHOT_UP_RIGHT 54
#define ACTOR_ANIM_SHOT_RIGHT 55
#define ACTOR_ANIM_SHOT_DOWN_RIGHT 56
#define ACTOR_ANIM_SHOT_DOWN 57
#define ACTOR_ANIM_SHOT_DOWN_LEFT 58
#define ACTOR_ANIM_SHOT_LEFT 59
#define ACTOR_ANIM_SHOT_UP_LEFT 60

#define ACTOR_ANIM_SHOW_GUN_UP 61
#define ACTOR_ANIM_SHOW_GUN_UP_RIGHT 62
#define ACTOR_ANIM_SHOW_GUN_RIGHT 63
#define ACTOR_ANIM_SHOW_GUN_DOWN_RIGHT 64
#define ACTOR_ANIM_SHOW_GUN_DOWN 65
#define ACTOR_ANIM_SHOW_GUN_DOWN_LEFT 66
#define ACTOR_ANIM_SHOW_GUN_LEFT 67
#define ACTOR_ANIM_SHOW_GUN_UP_LEFT 68

#define ACTOR_ANIM_HIDE_GUN_UP 69
#define ACTOR_ANIM_HIDE_GUN_UP_RIGHT 70
#define ACTOR_ANIM_HIDE_GUN_RIGHT 71
#define ACTOR_ANIM_HIDE_GUN_DOWN_RIGHT 72
#define ACTOR_ANIM_HIDE_GUN_DOWN 73
#define ACTOR_ANIM_HIDE_GUN_DOWN_LEFT 74
#define ACTOR_ANIM_HIDE_GUN_LEFT 75
#define ACTOR_ANIM_HIDE_GUN_UP_LEFT 76

#define ACTOR_ANIM_RELOAD_UP 77
#define ACTOR_ANIM_RELOAD_UP_RIGHT 78
#define ACTOR_ANIM_RELOAD_RIGHT 79
#define ACTOR_ANIM_RELOAD_DOWN_RIGHT 80
#define ACTOR_ANIM_RELOAD_DOWN 81
#define ACTOR_ANIM_RELOAD_DOWN_LEFT 82
#define ACTOR_ANIM_RELOAD_LEFT 83
#define ACTOR_ANIM_RELOAD_UP_LEFT 84

#define ACTOR_ANIM_STAND_GUN_UP 85
#define ACTOR_ANIM_STAND_GUN_UP_RIGHT 86
#define ACTOR_ANIM_STAND_GUN_RIGHT 87
#define ACTOR_ANIM_STAND_GUN_DOWN_RIGHT 88
#define ACTOR_ANIM_STAND_GUN_DOWN 89
#define ACTOR_ANIM_STAND_GUN_DOWN_LEFT 90
#define ACTOR_ANIM_STAND_GUN_LEFT 91
#define ACTOR_ANIM_STAND_GUN_UP_LEFT 92

#define ACTOR_ANIM_WALK_GUN_UP 93
#define ACTOR_ANIM_WALK_GUN_UP_RIGHT 94
#define ACTOR_ANIM_WALK_GUN_RIGHT 95
#define ACTOR_ANIM_WALK_GUN_DOWN_RIGHT 96
#define ACTOR_ANIM_WALK_GUN_DOWN 97
#define ACTOR_ANIM_WALK_GUN_DOWN_LEFT 98
#define ACTOR_ANIM_WALK_GUN_LEFT 99
#define ACTOR_ANIM_WALK_GUN_UP_LEFT 100

#define ACTOR_ANIM_POINT_GUN_UP 101
#define ACTOR_ANIM_POINT_GUN_UP_RIGHT 102
#define ACTOR_ANIM_POINT_GUN_RIGHT 103
#define ACTOR_ANIM_POINT_GUN_DOWN_RIGHT 104
#define ACTOR_ANIM_POINT_GUN_DOWN 105
#define ACTOR_ANIM_POINT_GUN_DOWN_LEFT 106
#define ACTOR_ANIM_POINT_GUN_LEFT 107
#define ACTOR_ANIM_POINT_GUN_UP_LEFT 108

#define ACTOR_ANIM_SHOW_HAND_UP 109
#define ACTOR_ANIM_SHOW_HAND_UP_RIGHT 110
#define ACTOR_ANIM_SHOW_HAND_RIGHT 111
#define ACTOR_ANIM_SHOW_HAND_DOWN_RIGHT 112
#define ACTOR_ANIM_SHOW_HAND_DOWN 113
#define ACTOR_ANIM_SHOW_HAND_DOWN_LEFT 114
#define ACTOR_ANIM_SHOW_HAND_LEFT 115
#define ACTOR_ANIM_SHOW_HAND_UP_LEFT 116

#define ACTOR_ANIM_HIDE_HAND_UP 117
#define ACTOR_ANIM_HIDE_HAND_UP_RIGHT 118
#define ACTOR_ANIM_HIDE_HAND_RIGHT 119
#define ACTOR_ANIM_HIDE_HAND_DOWN_RIGHT 120
#define ACTOR_ANIM_HIDE_HAND_DOWN 121
#define ACTOR_ANIM_HIDE_HAND_DOWN_LEFT 122
#define ACTOR_ANIM_HIDE_HAND_LEFT 123
#define ACTOR_ANIM_HIDE_HAND_UP_LEFT 124

#define ACTOR_ANIM_HIT_UP 125
#define ACTOR_ANIM_HIT_UP_RIGHT 126
#define ACTOR_ANIM_HIT_RIGHT 127
#define ACTOR_ANIM_HIT_DOWN_RIGHT 128
#define ACTOR_ANIM_HIT_DOWN 129
#define ACTOR_ANIM_HIT_DOWN_LEFT 130
#define ACTOR_ANIM_HIT_LEFT 131
#define ACTOR_ANIM_HIT_UP_LEFT 132

#define ACTOR_ANIM_DEAD 133

extern Actor *actor;
void ACTOR_Init(void);
void ACTOR_LoadActorAssets(const char *dat_name);
void ACTOR_SetGun(int actor_spr_num, int type);
void ACTOR_Load(int x, int y, int feet_gfx_id, int body_gfx_id, int head_gfx_id, int larm_gfx_id, int rarm_gfx_id, int facing);
void ACTOR_Update(void);
void ACTOR_DrawColissionPixels(void);
void ACTOR_DrawHitPixels(void);
void ACTOR_SetCombatMode(bool mode);
bool ACTOR_IsInCombatMode(void);
void ACTOR_SetBulletStatus(int pistol_bullets, int shotgun_bullets, int uzi_bullets, int snipper_bullets, int grenades);
void ACTOR_SetPosition(int x, int y, int facing);
void ACTOR_UnloadActor(void);
void ACTOR_SetFullWalkAnimation(int facing);
void ACTOR_SetFreeze(bool freeze);
void ACTOR_LeaveKey(void);
void ACTOR_Reload(void);


#endif
