#define ACTOR_TRANSP_COLOR 220
#define ACTOR_SPRITE_WIDTH 32
#define ACTOR_SPRITE_HEIGHT 32
#define ACTOR_TILESET_WIDTH 320
#define ACTOR_TILESET_HEIGHT 288
#define ACTOR_BULLET_GFX_WIDTH 32
#define ACTOR_BULLET_GFX_HEIGHT 8
#define ACTOR_BULLET_WIDTH 8
#define ACTOR_BULLET_HEIGHT 8
#define ACTOR_BULLET_ANIM_SPEED 4
#define ACTOR_SPEED 3
#define ACTOR_ANIMATION_SPEED 5
#define ACTOR_ACCURACY_SPEED 5
#define ACTOR_IDLE_TICKS 120
#define ACTOR_LIFE 80

#define ACTOR_ACTION_STAND 1
#define ACTOR_ACTION_LOOP 2
#define ACTOR_ACTION_SHOOT 3
#define ACTOR_ACTION_WALK 4
#define ACTOR_ACTION_PUNCH 5

#define ACTOR_GUN_BARE_HANDS 0
#define ACTOR_GUN_PISTOL 1
#define ACTOR_GUN_RIFLE 2
#define ACTOR_GUN_SHOTGUN 3
#define ACTOR_GUN_AK 4
#define ACTOR_GUN_MISILE 5
#define ACTOR_GUN_SNIPPER 6

#define ACTOR_UP_STAND_BASE_FRAME 0
#define ACTOR_UP_WALK_BASE_FRAME 1
#define ACTOR_UP_PUNCH1_BASE_FRAME 5
#define ACTOR_UP_PUNCH2_BASE_FRAME 8
#define ACTOR_UP_KICK_BASE_FRAME 10
#define ACTOR_UP_SHOOT_BASE_FRAME 13

#define ACTOR_UP_RIGHT_STAND_BASE_FRAME 15
#define ACTOR_UP_RIGHT_WALK_BASE_FRAME 16
#define ACTOR_UP_RIGHT_PUNCH1_BASE_FRAME 20
#define ACTOR_UP_RIGHT_PUNCH2_BASE_FRAME 23
#define ACTOR_UP_RIGHT_KICK_BASE_FRAME 25
#define ACTOR_UP_RIGHT_SHOOT_BASE_FRAME 28

#define ACTOR_RIGHT_STAND_BASE_FRAME 30
#define ACTOR_RIGHT_WALK_BASE_FRAME 31
#define ACTOR_RIGHT_PUNCH1_BASE_FRAME 35
#define ACTOR_RIGHT_PUNCH2_BASE_FRAME 38
#define ACTOR_RIGHT_KICK_BASE_FRAME 40
#define ACTOR_RIGHT_SHOOT_BASE_FRAME 43

#define ACTOR_DOWN_RIGHT_STAND_BASE_FRAME 45
#define ACTOR_DOWN_RIGHT_WALK_BASE_FRAME 46
#define ACTOR_DOWN_RIGHT_PUNCH1_BASE_FRAME 50
#define ACTOR_DOWN_RIGHT_PUNCH2_BASE_FRAME 53
#define ACTOR_DOWN_RIGHT_KICK_BASE_FRAME 55
#define ACTOR_DOWN_RIGHT_SHOOT_BASE_FRAME 58

#define ACTOR_DOWN_STAND_BASE_FRAME 60
#define ACTOR_DOWN_WALK_BASE_FRAME 61
#define ACTOR_DOWN_PUNCH1_BASE_FRAME 65
#define ACTOR_DOWN_PUNCH2_BASE_FRAME 68
#define ACTOR_DOWN_KICK_BASE_FRAME 70
#define ACTOR_DOWN_SHOOT_BASE_FRAME 73

#define ACTOR_RIGHT_LOOP_BASE_FRAME 75
#define ACTOR_UP_LOOP_BASE_FRAME 81

#define ACTOR_HIT_BASE_FRAME 87
#define ACTOR_DIE_BASE_FRAME 88

#define ACTOR_DOWN_LOOP_BASE_FRAME 90
