#define ACTOR_TRANSP_COLOR 220
#define ACTOR_SPRITE_WIDTH 32
#define ACTOR_SPRITE_HEIGHT 32
#define ACTOR_TILESET_WIDTH 320
#define ACTOR_TILESET_HEIGHT 288
#define ACTOR_BULLET_GFX_WIDTH 32
#define ACTOR_BULLET_GFX_HEIGHT 8
#define ACTOR_BULLET_WIDTH 8
#define ACTOR_BULLET_HEIGHT 8
#define ACTOR_BULLET_ANIM_SPEED 4
#define ACTOR_SPEED 3
#define ACTOR_ANIMATION_SPEED 5
#define ACTOR_ACCURACY_SPEED 5
#define ACTOR_IDLE_TICKS 120
#define ACTOR_LIFE 80

#define ACTOR_ACTION_STAND 1
#define ACTOR_ACTION_LOOP 2
#define ACTOR_ACTION_SHOOT 3
#define ACTOR_ACTION_WALK 4

#define ACTOR_GUN_BARE_HANDS 0
#define ACTOR_GUN_PISTOL 1
#define ACTOR_GUN_RIFLE 2
#define ACTOR_GUN_SHOTGUN 3
#define ACTOR_GUN_AK 4
#define ACTOR_GUN_MISILE 5
