#ifndef VIDEO_H
#define VIDEO_H

#define VIDEO_TEXT_MODE 0x03
#define VIDEO_GRAPHICS_MODE 0x13

#define VIDEO_MAP_BUFFER_WIDTH 336
#define VIDEO_MAP_BUFFER_HEIGHT 224

#define VIDEO_TRANSPARENT_COLOR 220

#define VIDEO_PANEL_WIDTH 80
#define VIDEO_PANEL_HEIGHT 32
#define VIDEO_PANEL_POS_X 8
#define VIDEO_PANEL_POS_Y 8

#define VIDEO_SCREEN_BUFFER_BACK 0
#define VIDEO_SCREEN_BUFFER_FORE 1
#define VIDEO_SCREEN_BUFFER_MASK 2

#endif