#define MAP_MAX_WIDTH 80
#define MAP_MAX_HEIGHT 80

#define MAP_TILE_WIDTH 16
#define MAP_TILE_WIDTH_BASE2 4
#define MAP_TILE_HEIGHT 16
#define MAP_TILE_HEIGHT_BASE2 4

#define MAP_MAX_BACK_TILESET_WIDTH 320
#define MAP_MAX_BACK_TILESET_HEIGHT 460
#define MAP_MAX_FORE_TILESET_WIDTH 128
#define MAP_MAX_FORE_TILESET_HEIGHT 128
#define MAP_MAX_MASK_TILESET_WIDTH 128
#define MAP_MAX_MASK_TILESET_HEIGHT 128

#define MAP_BACKGROUND_LAYER 0
#define MAP_FOREGROUND_LAYER 1
#define MAP_MASK_LAYER 2
#define MAP_COLISSION_LAYER 3
#define MAP_EVENT_HSPOT_LAYER 4
